# This is a basic workflow to help you get started with Actions

name: CI
  
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test_and_doc:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.9, 3.13]
    steps:
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Getting repository
      uses: actions/checkout@v4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Alingment notebook
      run: |
        cd notebooks
        python -m pytest --nbval AFold_Alignment_CPU.ipynb
    - name: Run Inference notebook
      run: |
        cd notebooks
        python -m pytest --nbval AFold_Confidence_Levels.ipynb
    - name: Run Analysis
      run: |  
        cd notebooks
        python -m pytest --nbval AFold_Diffusion_GPU.ipynb
